sudo: false
language: python
python: '2.7'
addons:
  apt:
    packages:
    - curl

install:
- pip install apache-libcloud
- pip install ansible
- pip install gcloud
- pip install pyopenssl
- export CLOUDSDK_CORE_DISABLE_PROMPTS=1
- export CLOUDSDK_PYTHON_SITEPACKAGES=1
- curl https://sdk.cloud.google.com | bash
- "~/google-cloud-sdk/bin/gcloud config set project maven-end-to-end"

script:
- ansible-playbook --version
